# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNPushApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNPushApp
  pod 'Firebase/Messaging' #buraya ekledik

  target 'RNPushAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
